export const siteConfig = {
  // Información personal
  name: "TAKASHOSHI",
  title: "ARTISTA VISUAL",
  description:
    "EXPLORANDO LA NARRATIVA VISUAL A TRAVÉS DE CORTOMETRAJES, ANIMACIONES E ILUSTRACIONES QUE CONECTAN EMOCIONES Y EXPERIENCIAS HUMANAS.",
  email: "TAKASHOSHI8@GMAIL.COM",

  // Redes sociales - Cambia por tus URLs reales
  social: {
    instagram: "https://instagram.com/takashoshi",
    twitter: "https://twitter.com/taka_shoshi",
    youtube: "https://youtube.com/@takashoshi",
    behance: "https://behance.net/mateovirto",
    objkt: "https://objkt.com/@takashoshi",
  },

  // Configuración de tienda
  store: {
    printPrice: 15, // Precio base en USD
    cryptoAddresses: {
      ethereum: "takashoshi.eth",
      tezos: "takashoshi.tez",
    },
    paymentMethods: {
      paypal: "https://paypal.me/takashoshi", // Cambiar por tu enlace real
      stripe: "https://buy.stripe.com/your-link", // Cambiar por tu enlace real
    },
  },

  // Biografía - Personaliza con tu historia
  bio: {
    title: "UN POCO DE MÍ",
    paragraphs: [
      "ME LLAMO MATEO VIRTO, TENGO 27 AÑOS Y NACÍ EN VICTORICA, UN PUEBLO DE LA PAMPA. ME FORMÉ UNIVERSITARIAMENTE COMO ABOGADO, PERO CON EL TIEMPO DESCUBRÍ QUE ME GUSTA PASAR EL TIEMPO CREANDO, ANIMANDO, DIBUJANDO. EXPERIMENTANDO. APRENDIENDO DE FORMA AUTODIDACTA.",
      "ME GUSTA CREAR MI PROPIO MUNDO. PASO EL DÍA IMAGINANDO, CREANDO ANIMACIONES CON MI CELULAR O EN LA COMPUTADORA PARA DIVERTIRME. ME FASCINA LA IDEA DE EMPEZAR A DIBUJAR SIN SABER CÓMO VA A TERMINAR.",
      "TENGO UN PROCESO ESPONTÁNEO Y SENCILLO. ME GUSTA JUGAR CON LAS COMPOSICIONES, PALETAS DE COLORES, NARRATIVAS, PERSPECTIVAS, PRINCIPIOS DE LA ANIMACIÓN.",
    ],
  },

  // Trabajos - Agrega tus proyectos reales
  works: {
    shorts: [
      {
        id: 1,
        title: "THE LAST MISSION",
        description:
          "220 FOTOGRAMAS (CREADOS UNO POR UNO) / 128X64PX / GRABACIÓN DE SONIDOS, SAMPLES Y EXPERIMENTACIÓN CON TECLADO MIDI",
        thumbnail: "/images/gallery/shorts/the-last-mission-thumb.gif",
        video: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/THE%20LAST%20MISSION-aXYxxxTMuIQWz1gNNsG9uoOb9DEKDY.mp4",
        year: "2025",
        duration: "22 SEGUNDOS",
      },
      {
        id: 2,
        title: "EL GRAN SALTO",
        description:
          "135 FOTOGRAMAS HECHOS UNO POR UNO / GRABACIONES DE VOZ, SAMPLES Y EDICIÓN DE SONIDO / CREADO EN 256X256PX Y ESCALADO A 1024X1024PX",
        thumbnail: "/images/gallery/shorts/el-gran-salto-thumb.gif",
        year: "2025",
        duration: "30 SEGUNDOS",
      },
    ],
    animations: [
      {
        id: 1,
        title: "METAMORFOSIS",
        description: "ANIMACIÓN MINIMALISTA CON FORMAS GEOMÉTRICAS EN TRANSFORMACIÓN",
        thumbnail: "/images/gallery/animations/metamorfosis.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 2,
        title: "MARS CALLING",
        description: "ANIMACIÓN RETRO SCI-FI CON ESTÉTICA DE LOS 80S",
        thumbnail: "/images/gallery/animations/mars-calling.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 3,
        title: "TRANSFOR-MAN",
        description: "AUTO ANIMADO CON PERSONALIDAD Y EXPRESIÓN",
        thumbnail: "/images/gallery/animations/transfor-man.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 5,
        title: "RADIO STAR",
        description: "HOMENAJE A LA CULTURA MUSICAL Y LOS MEDIOS DE COMUNICACIÓN",
        thumbnail: "/images/gallery/animations/radio-star.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 6,
        title: "BOTTLE FLIP",
        description: "ANIMACIÓN INSPIRADA EN TENDENCIAS VIRALES CONTEMPORÁNEAS",
        thumbnail: "/images/gallery/animations/bottle-flip.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 7,
        title: "ILL COCCODRILO COME FA",
        description: "ANIMACIÓN CONCEPTUAL SOBRE COMUNICACIÓN GLOBAL",
        thumbnail: "/images/gallery/animations/ill-coccodrilo-come-fa.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 8,
        title: "MAGIC ROLLING STAR",
        description: "FORMA ESTRELLADA EN MOVIMIENTO HIPNÓTICO",
        thumbnail: "/images/gallery/animations/magic-rolling-star.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 10,
        title: "BLUE COLLECTION",
        description: "PORTADA DE LA COLECCIÓN BLUE - SERIE TEMÁTICA AZUL",
        thumbnail: "/images/gallery/animations/blue-collection-portada.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 11,
        title: "MAILVOICE",
        description: "COMUNICACIÓN DIGITAL EN PAISAJE MINIMALISTA",
        thumbnail: "/images/gallery/animations/mailvoice.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 15,
        title: "CALESITA DE AGUA",
        description: "CARRUSEL ACUÁTICO CON SOMBRILLA ROJA FLOTANTE",
        thumbnail: "/images/gallery/animations/calesita-de-agua.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 20,
        title: "MATERIALES",
        description: "ESTUDIO MINIMALISTA DE HERRAMIENTAS DE DIBUJO",
        thumbnail: "/images/gallery/animations/materiales.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 21,
        title: "SPIN CAR",
        description: "AUTO PIXELADO EN MOVIMIENTO ROTATORIO",
        thumbnail: "/images/gallery/animations/spin-car.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 22,
        title: "MUSIC BAND",
        description: "MÚSICO TOCANDO TECLADO CON ESTILO MINIMALISTA",
        thumbnail: "/images/gallery/animations/music-band.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 23,
        title: "BIG WAVE COMING",
        description: "OLA GIGANTE APROXIMÁNDOSE A LA COSTA EN TONOS PÚRPURA",
        thumbnail: "/images/gallery/animations/big-wave-coming.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 24,
        title: "THE BUILDINGS",
        description: "PAISAJE URBANO COLORIDO CON EDIFICIOS VIBRANTES",
        thumbnail: "/images/gallery/animations/the-buildings.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 25,
        title: "VULCANO SPIT",
        description: "ERUPCIÓN DE VOLCÁN EN TONOS CÁLIDOS Y NARANJAS",
        thumbnail: "/images/gallery/animations/vulcano-spit.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 26,
        title: "COMO SERIA VIVIR EN UNA ISLA",
        description: "PEQUEÑA ISLA PARADISÍACA CON CABAÑA Y PALMERAS",
        thumbnail: "/images/gallery/animations/como-seria-vivir-en-una-isla.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 27,
        title: "CAIDA SUAVE",
        description: "PAISAJE URBANO CON EDIFICIOS Y ÁRBOLES EN PERSPECTIVA",
        thumbnail: "/images/gallery/animations/caida-suave.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 28,
        title: "AGENT 277",
        description: "RETRATO DIGITAL EN ESTILO MATRIX CON CÓDIGO BINARIO",
        thumbnail: "/images/gallery/animations/agent-277.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 29,
        title: "SAIYAJIN'S PROBLEMS",
        description: "HOMENAJE A DRAGON BALL CON PERSONAJES PIXELADOS",
        thumbnail: "/images/gallery/animations/saiyajins-problems.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 30,
        title: "PERFECT LAND",
        description: "AVIÓN SOBREVOLANDO UN CIELO CON NUBES ESTILIZADAS",
        thumbnail: "/images/gallery/animations/perfect-land.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 31,
        title: "SIEMPRE QUE LLOVIÓ, PARÓ",
        description: "PAISAJE MINIMALISTA CON CIELO Y TIERRA EN TRANSICIÓN",
        thumbnail: "/images/gallery/animations/siempre-que-llovio-paro.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 32,
        title: "CHOQUE DE PLACAS TECTÓNICAS",
        description: "MONTAÑAS NEVADAS EMERGIENDO EN UN PAISAJE DINÁMICO",
        thumbnail: "/images/gallery/animations/choque-de-placas-tectonicas.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 33,
        title: "FOLLOW THE SUN",
        description: "CAMINO ASCENDENTE HACIA EL SOL EN UN PAISAJE VERDE",
        thumbnail: "/images/gallery/animations/follow-the-sun.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 34,
        title: "ESCAPE PERFECTO",
        description: "PUENTE SOBRE AGUA AZUL ENTRE ESTRUCTURAS SIMÉTRICAS",
        thumbnail: "/images/gallery/animations/escape-perfecto.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 35,
        title: "ESCALADA",
        description: "FIGURA HUMANA EXPLORANDO UN PAISAJE DESÉRTICO",
        thumbnail: "/images/gallery/animations/escalada.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 36,
        title: "POOL SHOT",
        description: "BOLA 8 DE BILLAR SOBRE FONDO VERDE EN MOVIMIENTO",
        thumbnail: "/images/gallery/animations/pool-shot.gif",
        technique: "PIXEL ART",
        year: "2025",
      },
    ],
    illustrations: [
      {
        id: 1,
        title: "BETWEEN THE MOUNTAINS",
        description: "PAISAJE URBANO JAPONÉS CON ARQUITECTURA TRADICIONAL",
        image: "/images/gallery/illustrations/between-mountains.png",
        technique: "PIXEL ART",
        year: "2024",
      },
      {
        id: 2,
        title: "PING PONG SERVICE",
        description: "ARTE DEPORTIVO MINIMALISTA CON ESTÉTICA JAPONESA",
        image: "/images/gallery/illustrations/ping-pong.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 3,
        title: "TRAIN STATION",
        description: "ARQUITECTURA CLÁSICA CON PERSPECTIVA DRAMÁTICA",
        image: "/images/gallery/illustrations/train-station.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 4,
        title: "IT'S ABOUT TO RAIN IN TOKYO",
        description: "ESCENA URBANA CIRCULAR CON ATMÓSFERA PRE-TORMENTA",
        image: "/images/gallery/illustrations/tokyo-rain.png",
        technique: "PIXEL ART",
        year: "2024",
      },
      {
        id: 5,
        title: "PARADISE PIXELS",
        description: "PAISAJE FANTÁSTICO CON UNICORNIOS Y ARCOÍRIS",
        image: "/images/gallery/illustrations/paradise-pixels.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 6,
        title: "TOKYO IN MY MIND",
        description: "VIDA URBANA DETALLADA CON SIGNOS JAPONESES",
        image: "/images/gallery/illustrations/the-block.png",
        technique: "PIXEL ART",
        year: "2024",
      },
      {
        id: 7,
        title: "MEMORIA, VERDAD Y JUSTICIA",
        description: "ARTE CONMEMORATIVO POR LOS DERECHOS HUMANOS",
        image: "/images/gallery/illustrations/memoria-verdad-justicia.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 8,
        title: "HORSE RACE",
        description: "ESCENA DINÁMICA DE CARRERAS DE CABALLOS",
        image: "/images/gallery/illustrations/horse-race.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 9,
        title: "SUNSET IN THE DESERT",
        description: "ATARDECER SERENO CON CIELO ESTRELLADO",
        image: "/images/gallery/illustrations/sunset-desert.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 10,
        title: "RACE IN THE SNOW",
        description: "ESCENA INVERNAL MONOCROMÁTICA EN LAS MONTAÑAS",
        image: "/images/gallery/illustrations/race-snow.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 11,
        title: "TENNIS CLASICO",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CANCHA DE TENIS CON DOS JUGADORES.",
        image: "/images/gallery/illustrations/tennis-clasico.png",
        technique: "PIXEL ART",
        year: "2025", // Asumo el año actual si no se especifica
      },
      {
        id: 12,
        title: "FIGHT NIGHT",
        description: "ILUSTRACIÓN PIXEL ART ABSTRACTA CON UN MARCO DE COLORES Y FIGURAS PIXELADAS.",
        image: "/images/gallery/illustrations/fight-night.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 13,
        title: "PADEL MATCH",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CANCHA DE PÁDEL CON JUGADORES.",
        image: "/images/gallery/illustrations/padel-match.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 14,
        title: "BASKETBALL PICKUP",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CANCHA DE BALONCESTO.",
        image: "/images/gallery/illustrations/basketball-pickup.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 15,
        title: "VOLLEYBALL PRACTICE",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CANCHA DE VOLEIBOL CON VARIOS JUGADORES.",
        image: "/images/gallery/illustrations/volleyball-practice.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 16,
        title: "FOOTBALL DERBY",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CANCHA DE FÚTBOL CON JUGADORES.",
        image: "/images/gallery/illustrations/football-derby.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 17,
        title: "THE RACE",
        description: "PIXEL ART DE UNA PISTA DE CARRERAS CIRCULAR CON VARIOS AUTOS.",
        image: "/images/gallery/illustrations/the-race.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 18,
        title: "THE LAST SURVIVOR",
        description: "ILUSTRACIÓN PIXEL ART DE UNA FIGURA EN LA CIMA DE UNA PIRÁMIDE SOBRE LAS NUBES.",
        image: "/images/gallery/illustrations/the-last-survivor.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 19,
        title: "FRIENDS MOMENT",
        description: "ESCENA PIXEL ART DE AMIGOS DISFRUTANDO EN UNA PLAYA JUNTO A ACANTILADOS.",
        image: "/images/gallery/illustrations/friends-moment.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 20,
        title: "ATARDECER",
        description: "ILUSTRACIÓN PIXEL ART DE UN ATARDECER CON UN ÁRBOL SOLITARIO Y UN CARTEL DE EVENTO.",
        image: "/images/gallery/illustrations/atardecer.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 21,
        title: "CASA EN LA PLAYA",
        description: "ILUSTRACIÓN PIXEL ART DE UNA CASA MODERNA EN LA PLAYA CON EL OCÉANO DE FONDO.",
        image: "/images/gallery/illustrations/casa-en-la-playa.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 22,
        title: "TABLE TENNIS SCHOOL",
        description: "PATRÓN REPETITIVO DE MESAS DE PING PONG CON TEXTO 'TABLE TENNIS SCHOOL'.",
        image: "/images/gallery/illustrations/table-tennis-school.png",
        technique: "PIXEL ART",
        year: "2025",
      },
      {
        id: 23,
        title: "LA BOMBONERA",
        description: "ILUSTRACIÓN PIXEL ART DEL ESTADIO DE FÚTBOL LA BOMBONERA.",
        image: "/images/gallery/illustrations/la-bombonera.png",
        technique: "PIXEL ART",
        year: "2025",
      },
    ],
  },

  // Productos de la tienda - Simplificado
  products: {
    prints: {
      name: "PRINTS PIXEL ART",
      price: 15,
      description: "IMPRESIONES DE ALTA CALIDAD DE MIS ILUSTRACIONES PIXEL ART",
      note: "PRECIO NO INCLUYE ENVÍO NACIONAL/INTERNACIONAL",
      sizes: ["A4 (21x30cm)", "A3 (30x42cm)", "CUADRADO (25x25cm)"],
    },
    tshirts: [
      {
        id: "tshirt-domador",
        name: "REMERA EL DOMADOR",
        price: 25,
        design: "/images/designs/el-domador.png",
        colors: ["blanco", "negro", "azul", "rojo"],
        description: "REMERA 100% ALGODÓN CON DISEÑO EL DOMADOR",
      },
      {
        id: "tshirt-pingpong",
        name: "REMERA PING PONG",
        price: 25,
        design: "/images/designs/ping-pong-serve.png",
        colors: ["blanco", "negro", "azul", "rojo"],
        description: "REMERA 100% ALGODÓN CON DISEÑO PING PONG",
      },
      {
        id: "tshirt-logo",
        name: "REMERA TAKASHOSHI",
        price: 25,
        design: "/images/designs/takashoshi-logo.png",
        colors: ["blanco", "negro", "azul", "rojo"],
        description: "REMERA 100% ALGODÓN CON LOGO TAKASHOSHI",
      },
    ],
  },
}
